### ISSUE TITLE
How to run this project in Amazon server EC2?

### ISSUE THREAD

**Issue by shousunny** [gusibi/momo#3]
申请了Ａｍａｚｏｎ　ＥＣ２服务器，如何将这个项目放在服务器上运行？

**Comment by gusibi** [comment]
更新代码
```
git clone git@github.com:gusibi/momo.git
```

安装python环境（python3）

## 安装依赖

pip install -r requirements.txt -i http://pypi.douban.com/simple --trusted-host pypi.douban.com

运行
```
cd momo/
python manage.py
```

**Comment by shousunny** [comment]
我在本地按这些命令跑通了。在服务器上也是运行这个命令是吗？

**Comment by gusibi** [comment]
都一样的 你需要在ec2 配置nginx  然后就可以用域名访问了

**Comment by shousunny** [comment]
求nginx配置教程，

**Comment by gusibi** [comment]
建議打開google 或者 百度 搜索 nginx 配置

https://segmentfault.com/a/1190000002797601

**Comment by shousunny** [comment]
http://www.jianshu.com/p/be9dd421fb8d 可以参考这个教程配置吧。gunicorn有必要装吗？

**Comment by gusibi** [comment]
我感觉没必要

**Comment by shousunny** [comment]
大神，公众号ＵＲＬ如何设置，是按照这样的格式吗？http://myserver.com:80/weixin

**Comment by gusibi** [comment]
http://myserver.com/weixin  不需要加 :80 这个是默认的

**Comment by shousunny** [comment]
昨天试了，好像一直提示token错误

**Comment by shousunny** [comment]
在亚马逊ＥＣ２服务器的IPv4 公有 IP为：13.xx.x.xxx,微信公众号接入ＵＲＬ设置为：http://13.xx.x.xxx/weixin　　。
令牌为自己任意设置的一段字母，比如“shousunny”,采用兼容模式。但总是提示ｔｏｋｅｎ验证错误，求大神指教。【ｎｇｉｎｘ已搭建成功，外网能够通过ＵＲＬ与ｍｏｍｏ对话。】

点击提交微信服务器配置后，服务器端显示：
“File "/usr/local/lib/python3.5/dist-packages/sanic/router.py", line 339, in _get
    raise NotFound('Requested URL {} not found'.format(url))
sanic.exceptions.NotFound: Requested URL /weixin not found
”

**Comment by gusibi** [comment]
sanic.exceptions.NotFound: Requested URL /weixin not found  这个错误是 url 未找到 你nginx 配置了域名 就要用域名访问 不要直接填写 ip  http://13.xx.x.xxx/weixin  这个 换成 http://www.yourdomain.com/weixin  这样

**Comment by shousunny** [comment]
ＥＣ２服务器的域名http://ec2-13-xx-x-xxx.us-east-2.compute.amazonaws.com/,使用这个ＵＲＬ时，微信提示，“当前填写的URL存在严重安全风险，无法设置

该URL所属域名在限定的时间内（2017/6/27之前），未接入公众号第三方平台（在open.weixin.qq.com接入），存在安全风险，可能影响你的公众号账号安全，已被禁止设置。”

使用ＩＰ填写微信ＵＲＬ时　，服务端能收到微信发来的请求，
如下：
`2017-07-23 06:11:57 - (network)[INFO][127.0.0.1:33130]: GET http://13.x.x.xxx/weixin?signature=6b08a72417cde8be50d9fabefdbc941e1d945077&echostr=4637227140318232556&timestamp=1500790316&nonce=2372101262  404 38`，
ｓｅｔｔｉｎｇ.py文件里对应的ａｐｐｉｄ，ｓｅｃｒｅｔ等信息也已经修改，还是显示ＵＲＬ未找到。

**Comment by gusibi** [comment]
那url你直接访问可以么？你手动请求下，先确定你设置的url 是正确的 如果 你没改过代码 url 应该是 http://13.xx-xx/weixin/request

**Comment by shousunny** [comment]
微信端提交设置后，服务器端显示：
`ＧＥＴ　http://13.x.x.xxx/weixin/request?signature=63fca038c26906d2b27accce2d9f8babe81a8cc5&echostr=1467623147122158326&timestamp=1500722762&nonce=1632924231`
手动复制该链接，输入浏览器，返回值为`fail`

**Comment by shousunny** [comment]
修改了，ｓｅｔｔｉｎｇ.py中的ａｐｐｉｄ和ｔｏｋｅｎ等值后，成功提交了微信公众号的ｕｒｌ配置。不过在微信输入消息后，显示“该公众号暂时无法提供服务，”，又迈出了一步。。。谢谢大神！
微信的ＵＲＬ设置格式应该为：`http://13.xx-xx/weixin/request`
最后发现有个ｌｘｍｌ未安装，ｐｉｐ　ｉｎｓｔａｌｌ后，一切就运行成功了，
感谢大神耐心指教！！好牛掰！！！！

**Comment by gusibi** [comment]
棒
