### ISSUE TITLE
请问能通过微信人工训练机器人吗？

### ISSUE THREAD

**Issue by shousunny** [gusibi/momo#4]
如果有，微信消息回复的格式是怎样的？
按照mweixin.py中规定的格式输入：
`momo_learn = re.compile(r'^momoya:"(?P<ask>\S*)"<"(?P<answer>\S*)"')`
训练语句输入：`momoya:"ask"<"answer"`
服务器端报错：    
```
return getattr(self, methodname, None)()
  File "/home/ubuntu/momo/momo/views/mweixin.py", line 114, in _text_msg_handler
    response = reply_content.set(conversation)
  File "/home/ubuntu/momo/momo/views/mweixin.py", line 70, in set
    momo_chat.set_trainer(ListTrainer)
NameError: name 'momo_chat' is not defined
```
个人猜测ｍｗｅｉｘｉｎ.ｐｙ中的这段代码是不是有问题：
```
def set(self, conversation):
        if self.momo:
            momo_chat.set_trainer(ListTrainer)
            momo_chat.train(conversation)
            return '魔魔学会了！'
```
，请大神指教！

个人觉得，由用户通过微信训练机器人比较好玩，

**Comment by gusibi** [comment]
这个需要 加上 

from momo.helpers import momo_chat

这一句漏掉了

**Comment by shousunny** [comment]
恩，我把训练的函数写到了ｈｅｌｐｅｒ里边，并在ｍｗｅｉｘｎ里导入，也成功了。
已经能够通过微信训练机器人了，美中不足的是，机器人好像只能记住第一次训练提供的答案，后续的训练不会覆盖前面的数据。比如：第一次训练用了`momoya:"gusibi"<"大神"，`
第二次训练改用`momoya:"gusibi"<"精英"，`
机器人只会记住第一次的答案，大神。

**Comment by gusibi** [comment]
是😂  chatterbot 是有这个问题
