### ISSUE TITLE
有关便签图片的问题

### ISSUE THREAD

**Issue by cs-usst** [gusibi/momo#7]
实际使用中发现两个问题，一是标点会出现在行首，不符合规范。二是英文会时常被分割至下一行。有办法解决吗？
谢谢

**Comment by gusibi** [comment]
现在这个是根据字符宽度来判断的，有两个简单的思路：

1. 针对标点符号，维护一个标点符号的列表，如果在这个列表中的标点出现在了行首，直接放到上一行（如果是省略号可能会有问题
2. 针对单词，在被分割到下一行的时候可以在上一行加一个 “-” 作为连字符

**Comment by cs-usst** [comment]
谢谢。用[这边](https://gist.github.com/oldj/9c4d012d6fff059ccea7)的改了（他的代码用了pygame，其中有部分不支持python3）
